export const data = [
    {
        day: 1,
        gift: "hello"
    },
    {
        day: 2,
        gift: "hello"
    },    {
        day: 3,
        gift: "hello"
    },    {
        day: 4,
        gift: "hello"
    },    {
        day: 5,
        gift: "hello"
    },    {
        day: 6,
        gift: "hello"
    },    {
        day: 7,
        gift: "hello"
    },    {
        day: 8,
        gift: "hello"
    },    {
        day: 9,
        gift: "hello"
    },    {
        day: 10,
        gift: "hello"
    },    {
        day: 11,
        gift: "hello"
    },    {
        day: 12,
        gift: "hello"
    },    {
        day: 13,
        gift: "hello"
    },    {
        day: 14,
        gift: "hello"
    },    {
        day: 15,
        gift: "hello"
    },    {
        day: 16,
        gift: "hello"
    },    {
        day: 17,
        gift: "hello"
    },    {
        day: 18,
        gift: "hello"
    },    {
        day: 19,
        gift: "hello"
    },    {
        day: 20,
        gift: "hello"
    },    {
        day: 21,
        gift: "hello"
    },    {
        day: 22,
        gift: "hello"
    },    {
        day: 23,
        gift: "hello"
    },    {
        day: 24,
        gift: "hello"
    },    {
        day: 25,
        gift: "hello"
    },    {
        day: 26,
        gift: "hello"
    },    {
        day: 27,
        gift: "hello"
    },    {
        day: 28,
        gift: "hello"
    },    {
        day: 29,
        gift: "hello"
    },    {
        day: 30,
        gift: "hello"
    },    {
        day: 31,
        gift: "hello"
    },
]